### ISSUE TITLE
Strict Transport Security: REDACTED

### ISSUE THREAD

**Issue by jasonfrankel** [Azure-Samples/digital-twins-samples#22]
After setting up an instance of Azure Digital Twins and an app registration, I then configured the SampleClientApp solution, built it, and ran it. 
 
After running it I typed `CreateModels Room Floor`. The result was a service request failed with a 403 forbidden error (output shown below). 
 
 ```
Please enter a command or 'help'. Commands are not case sensitive
CreateModels Room Floor
Reading from F:\dev\dt\Azure_Digital_Twins_samples\AdtSampleApp\SampleClientApp\bin\Debug\netcoreapp3.1\Models
Submitting models: Room.json, Floor.json...
 
Response 403: Service request failed.
Status: 403 (Forbidden)
 
Headers:
Strict-Transport-Security: REDACTED
Date: Mon, 06 Jul 2020 00:40:40 GMT
Content-Length: 0
```
The instructions I followed to get authentication setup are located at [_how to authenticate a client_](https://docs.microsoft.com/en-us/azure/digital-twins/how-to-authenticate-client).

The output of `az version` is below:
```
{
  "azure-cli": "2.8.0",
  "azure-cli-command-modules-nspkg": "2.0.3",
  "azure-cli-core": "2.8.0",
  "azure-cli-nspkg": "3.0.4",
  "azure-cli-telemetry": "1.0.4",
  "extensions": {
    "azure-iot": "0.9.6"
  }
}
```

**Comment by JMayrbaeurl** [comment]
Did you add the RBAC setup to ADT, too? See https://docs.microsoft.com/en-us/azure/digital-twins/concepts-security#authorization-rbac-roles-for-azure-digital-twins

**Comment by jasonfrankel** [comment]
Thank you. That solved the problem.
