### ISSUE TITLE
Temperature Update

### ISSUE THREAD

**Issue by Norrasahah** [Azure-Samples/digital-twins-samples#43]
After follow instruction on 'Tutorial: Connect an end-to-end solution', at last stage I run 'ObserveProperties thermostat67 Temperature room21 Temperature' but only get an update on thermostat67 only while room21 got 0 temperature. Base on my understanding, the temperature for room21 is will updated to match the updates to thermostat67. Can someone explains on this? below is my console result.

![temperature](https://user-images.githubusercontent.com/34327635/91941916-9efdd280-ed2c-11ea-9459-290d32c35cb3.PNG)

**Comment by alexkarcher-msft** [comment]
Hi @Norrasahah . That final value is updated through your attached function app. Can you look through the Function's App Insights logs and let me know if there are any executions? Are there error messages?

**Comment by dimiboi** [comment]
@alexkarcher-msft, I have also encountered the same problem as reported. There is actually an issue with the sample code. I created #56 to address it.
