### ISSUE TITLE
command need to be replaced

### ISSUE THREAD

**Issue by himanshuahlawat31** [Azure-Samples/digital-twins-samples#62]
Hi , in Create Azure function step the command need to be replaced with this as the current command will fail

**az functionapp create --consumption-plan-location eastus --name $twinupdatefunctionname --os-type Windows --resource-group adtholrg --runtime dotnet --functions-version 3 --storage-account adthol624storage**

**Comment by cranberry13** [comment]
The correct functionapp commands are below:

az functionapp create --resource-group $rgname --consumption-plan-location $location --name $telemetryfunctionname --storage-account $functionstorage --functions-version 3

az functionapp config appsettings set -g $rgname -n $telemetryfunctionname --settings "ADT_SERVICE_URL=https://<your-Azure-Digital-Twins-instance-hostname>"

az functionapp create --resource-group $rgname --consumption-plan-location $location --runtime dotnet --functions-version 3 --name $twinupdatefunctionname --storage-account  $functionstorage

**Comment by Satya-Kolluri** [comment]
@himanshuahlawat31  - Documentation is up to date now. Functions-version is optional but will be defaulted as of now.
