### ISSUE TITLE
TwinsFunction name issue

### ISSUE THREAD

**Issue by gary918** [Azure-Samples/digital-twins-samples#65]
Hi, all,
In the following command, use 'TwinsFunction' instead of 'twinsfunction', to make sure the function names are matched.
`$function=$(az functionapp function show -n $telemetryfunctionname -g $rgname --function-name twinsfunction --query id -o tsv)`

**Comment by cranberry13** [comment]
Correct functionapp command should be (with the case sensitive functionname in caps)

$function=$(az functionapp function show -n $telemetryfunctionname -g $rgname --function-name TwinsFunction --query id -o tsv)

**Comment by Satya-Kolluri** [comment]
$function=$(az functionapp function show -n $telemetryfunctionname -g $rgname --function-name TwinsFunction --query id -o tsv)
