### ISSUE TITLE
"Subdomain not found"

### ISSUE THREAD

**Issue by Farmy** [Azure-Samples/digital-twins-samples#67]
Hi everyone,

when running the SampleClientApp all I get is
```Error 404: Service request failed.
Status: 404 (Not Found)

Content:
{ "statusCode": 404, "message": "Sub-domain not found." }
````

In fiddler I see the url called was
`https://xyz.api.weu.digitaltwins.azure.net/models?api-version=2020-10-31`

The azure digital twins explorer works fine with the same url. Any idea what is going on?

**Comment by ksaye** [comment]
Same issue today.

**Comment by ksaye** [comment]
So in my case the Environment Variable for the Azure Function was wrong.  Changing this value and restarting the Azure function worked for me.  Seems to be a problem with the ARM template?  Shown below, it defaulted to West US 2 yet I deployed in south central US.

![image](https://user-images.githubusercontent.com/15837044/112030911-beadea00-8b08-11eb-93d5-5dc4ea5fee21.png)

**Comment by akiskips** [comment]
I came across this issue too, this seems to be a known issue when the user account belongs to a different Azure AD tenant from the DT instance.
In the troubleshoot page of the Docs there are two solutions described:

https://docs.microsoft.com/en-us/azure/digital-twins/troubleshoot-error-404

**Comment by Satya-Kolluri** [comment]
This is a known issue, troubleshoot docs has two  possible solutions provided for this issue. 

Refer the [troubleshoot page. ](https://docs.microsoft.com/en-us/azure/digital-twins/troubleshoot-error-404)
